package project.euler.problem;

import java.util.List;
import project.euler.FibonacciUtil;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:<br/>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...<br/>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @author cp318674
 */
public class Problem02 extends AProblem {

    @Override
    public String answer() {
        Integer sum = 0;
        List<Integer> fibRange = FibonacciUtil.generateFibonacciRangeUnder(4000000);
        for (Integer number : fibRange) {
            if (number % 2 == 0) {
                sum += number;
            }
        }
        return "" + sum;
    }
}
